export const GET_TOURNAMENTLIST_SUCCESS =
  'tournamentList/GET_TOURNAMENTLIST_SUCCESS'
export const GET_TOURNAMENTLIST_FAILED =
  'tournamentList/GET_TOURNAMENTLIST_FAILED'
export const GET_TOURNAMENTLIST = 'tournamentList/GET_TOURNAMENTLIST'
