export const GET_TOURNAMENT_DETAILS_SUCCESS =
  'tournamentDetails/GET_TOURNAMENT_DETAILS_SUCCESS'
export const GET_TOURNAMENT_DETAILS_FAILED =
  'tournamentDetails/GET_TOURNAMENT_DETAILS_FAILED'
export const GET_TOURNAMENT_DETAILS = 'tournamentDetails/GET_TOURNAMENT_DETAILS'
